# Generated by Django 5.0.3 on 2024-03-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='DepartmentDetails',
            field=models.CharField(default='SOME STRING', max_length=1000),
        ),
        migrations.AddField(
            model_name='departments',
            name='DepartmentMembers',
            field=models.IntegerField(default=0),
        ),
    ]
